// <auto-generated />
using System;
using Kvanto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kvanto.Data.Migrations
{
    [DbContext(typeof(KvantoDbContext))]
    partial class KvantoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Kvanto.Models.AppSettings", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");
                    b.Property<string>("AppTheme").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                    b.Property<string>("HotkeySkip").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                    b.Property<string>("HotkeyStartStop").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                    b.Property<int>("LongBreakInterval").HasColumnType("INTEGER");
                    b.Property<int>("LongBreakMinutes").HasColumnType("INTEGER");
                    b.Property<bool>("PlaySoundOnEnd").HasColumnType("INTEGER");
                    b.Property<int>("ShortBreakMinutes").HasColumnType("INTEGER");
                    b.Property<bool>("ShowDesktopNotifications").HasColumnType("INTEGER");
                    b.Property<bool>("StartMinimizedToTray").HasColumnType("INTEGER");
                    b.Property<bool>("StartWithWindows").HasColumnType("INTEGER");
                    b.Property<int>("WorkDurationMinutes").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.ToTable("Settings");
                    b.HasData(new
                    {
                        Id = 1,
                        AppTheme = "Dark",
                        HotkeySkip = "Ctrl+Alt+N",
                        HotkeyStartStop = "Ctrl+Alt+S",
                        LongBreakInterval = 4,
                        LongBreakMinutes = 15,
                        PlaySoundOnEnd = true,
                        ShortBreakMinutes = 5,
                        ShowDesktopNotifications = true,
                        StartMinimizedToTray = false,
                        StartWithWindows = false,
                        WorkDurationMinutes = 25
                    });
                });

            modelBuilder.Entity("Kvanto.Models.TaskItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                    b.Property<string>("Color").IsRequired().HasMaxLength(7).HasColumnType("TEXT");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<DateTime?>("DueDate").HasColumnType("TEXT");
                    b.Property<int>("EstimatedPomodoros").HasColumnType("INTEGER");
                    b.Property<int>("Priority").HasColumnType("INTEGER");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Kvanto.Models.PomodoroSession", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime?>("EndTime").HasColumnType("TEXT");
                    b.Property<bool>("IsCompleted").HasColumnType("INTEGER");
                    b.Property<string>("Notes").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<int>("PlannedDurationMinutes").HasColumnType("INTEGER");
                    b.Property<DateTime>("StartTime").HasColumnType("TEXT");
                    b.Property<int>("TaskItemId").HasColumnType("INTEGER");
                    b.Property<int>("Type").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("TaskItemId");
                    b.ToTable("PomodoroSessions");
                });

            modelBuilder.Entity("Kvanto.Models.PomodoroSession", b =>
                {
                    b.HasOne("Kvanto.Models.TaskItem", "TaskItem")
                        .WithMany("Sessions")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Kvanto.Models.TaskItem", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
